from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = REPO_ROOT / "data"
RAW_DIR = DATA_DIR / "raw"
INTERIM_DIR = DATA_DIR / "interim"
PROCESSED_DIR = DATA_DIR / "processed"
CANDIDATE_DIR = PROCESSED_DIR / "candidate"
ACTION_DIR = PROCESSED_DIR / "action"
ARTIFACTS_DIR = REPO_ROOT / "artifacts"
ANNOTATION_DIR = ARTIFACTS_DIR / "annotation"
PREDICTIONS_DIR = ARTIFACTS_DIR / "predictions"
RUNS_DIR = REPO_ROOT / "runs"
DOCS_DIR = REPO_ROOT / "docs"
GROUND_TRUTH_DIR = REPO_ROOT.parents[1] / "ground-truth"
DEFAULT_UPCHIEVE_MATH_GROUND_TRUTH_DIR = GROUND_TRUTH_DIR / "ground-truth-math-upchieve-1000"
DEFAULT_SAGA27_MATH_GROUND_TRUTH_DIR = GROUND_TRUTH_DIR / "ground-truth-math-saga-27"
LEGACY_DIR = REPO_ROOT / "legacy"
LEGACY_DATA_DIR = LEGACY_DIR / "data"
LEGACY_PROCESSED_DIR = LEGACY_DATA_DIR / "processed"
LEGACY_CANDIDATE_DIR = LEGACY_PROCESSED_DIR / "candidate"
LEGACY_ACTION_DIR = LEGACY_PROCESSED_DIR / "action"
LEGACY_ARTIFACTS_DIR = LEGACY_DIR / "artifacts"
LEGACY_ANNOTATION_DIR = LEGACY_ARTIFACTS_DIR / "annotation"
LEGACY_EXPERIMENTS_DIR = LEGACY_ARTIFACTS_DIR / "experiments"
LEGACY_RUNS_DIR = LEGACY_DIR / "runs"
LEGACY_DOCS_DIR = LEGACY_DIR / "docs"

EXPECTED_SPLITS = ("train", "dev", "test")
DEFAULT_CANDIDATE_LABELS = ("O", "B-SUSPECT", "I-SUSPECT")
DEFAULT_ACTION_LABELS = ("REDACT", "KEEP", "REVIEW")
DEFAULT_SEMANTIC_ROLE_LABELS = ("PRIVATE", "CURRICULAR", "AMBIGUOUS")

RESULTS_HEADER = "commit\tstage\tprimary_metric\tstatus\tdescription\n"
